--1. Coloque em uso o banco de dados PEDIDOS;
 USE PEDIDOS
 
 
--2. Liste os campos NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL da tabela TB_PEDIDO, seguidos de NOME --do vendedor da tabela TB_VENDEDOR;
 SELECT PED.NUM_PEDIDO
      , PED.DATA_EMISSAO
   , PED.VLR_TOTAL
   , VEND.NOME
 FROM TB_PEDIDO AS PED
 INNER JOIN TB_VENDEDOR AS VEND
 ON VEND.CODVEN = PED.CODVEN
 
 
 --3. Liste os campos NUM_PEDIDO, DATA_EMISSAO e VLR_TOTAL da tabela TB_PEDIDO, seguidos de NOME --do cliente da tabela TB_CLIENTE;
 SELECT PED.NUM_PEDIDO
      , PED.DATA_EMISSAO
   , PED.VLR_TOTAL
   , CLI.NOME
 FROM TB_PEDIDO AS PED
 INNER JOIN TB_CLIENTE AS CLI 
ON CLI.CODCLI = PED.CODCLI


--4. Liste os pedidos com o nome do vendedor e o nome do cliente;
 SELECT PED.NUM_PEDIDO
      , PED.DATA_EMISSAO
   , PED.VLR_TOTAL
   , CLI.NOME AS NOME_CLIENTE
   , VEND.NOME AS NOME_VENDEDOR
 FROM TB_PEDIDO AS PED
 INNER JOIN TB_CLIENTE AS CLI 
ON CLI.CODCLI = PED.CODCLI
 INNER JOIN TB_VENDEDOR AS VEND
 ON PED.CODVEN=VEND.CODVEN
 
 
 --5. Liste os itens de pedido (TB_ITENSPEDIDO) com o nome do produto (TB_PRODUTO.DESCRICAO);
 SELECT ITEM.*
    , PROD.DESCRICAO
 FROM TB_ITENSPEDIDO AS ITEM
 INNER JOIN TB_PRODUTO AS PROD 
ON PROD.ID_PRODUTO = ITEM.ID_PRODUTO


--6. Liste os itens pedidos, o nome do produto e a cor (TB_COR);
 SELECT ITEM.*
     , PROD.DESCRICAO 
  , COR.COR 
FROM TB_ITENSPEDIDO AS ITEM
 INNER JOIN TB_PRODUTO AS PROD
 ON PROD.ID_PRODUTO = ITEM.ID_PRODUTO
 INNER JOIN TB_COR AS COR 
ON COR.CODCOR = ITEM.CODCOR


--7. Liste os campos ID_PRODUTO e DESCRICAO da tabela TB_PRODUTO, seguidos da descrição do tipo --de produto (TB_TIPOPRODUTO.TIPO);
 SELECT PROD.ID_PRODUTO 
      , PROD.DESCRICAO  
   , TIPO.TIPO
 FROM TB_PRODUTO AS PROD 
INNER JOIN TB_TIPOPRODUTO AS TIPO 
ON TIPO.COD_TIPO = PROD.COD_TIPO


--8. Liste os campos ID_PRODUTO e DESCRICAO da tabela TB_PRODUTO, seguidos da descrição do tipo --de produto (TB_TIPOPRODUTO.TIPO) e do nome da unidade de medida (TB_UNIDADE.UNIDADE);
 SELECT PROD.ID_PRODUTO 
      , PROD.DESCRICAO  
   , TIPO.TIPO
  , UNID.UNIDADE
 FROM TB_PRODUTO AS PROD 
INNER JOIN TB_TIPOPRODUTO AS TIPO 
ON TIPO.COD_TIPO = PROD.COD_TIPO
 INNER JOIN TB_UNIDADE AS UNID
 ON  PROD.COD_UNIDADE=UNID.COD_UNIDADE
 
 
--9. Liste os campos NUM_PEDIDO, NUM_ITEM, COD_PRODUTO, QUANTIDADE e PR_UNITARIO da tabela TB_ITENSPEDIDO,-- e os campos ID_PRODUTO e DESCRICAO da tabela TB_PRODUTO, seguidos da descrição do tipo de produto--(TB_TIPOPRODUTO.TIPO) e do nome da unidade de medida (TB_UNIDADE.UNIDADE);

 SELECT ITEM.NUM_PEDIDO 
      , ITEM.NUM_ITEM
   , ITEM.COD_PRODUTO
   , ITEM.QUANTIDADE 
   , ITEM.PR_UNITARIO
   , PROD.ID_PRODUTO 
   , PROD.DESCRICAO  
   , TIPO.TIPO 
   , UNID.UNIDADE
 FROM TB_PRODUTO AS PROD 
INNER JOIN TB_TIPOPRODUTO AS TIPO
 ON TIPO.COD_TIPO = PROD.COD_TIPO
 INNER JOIN TB_UNIDADE AS UNID
 ON UNID.COD_UNIDADE = PROD.COD_UNIDADE
 INNER JOIN TB_ITENSPEDIDO AS ITEM
 ON ITEM.ID_PRODUTO = PROD.ID_PRODUTO
 
 
--10. Liste os campos NUM_PEDIDO, NUM_ITEM, COD_PRODUTO, QUANTIDADE e PR_UNITARIO da tabela--TB_ITENSPEDIDO, e os campos ID_PRODUTO e DESCRICAO da tabela TB_PRODUTO, seguidos da descrição do tipo --de produto (TB_TIPOPRODUTO.TIPO), do nome da unidade de medida (TB_UNIDADE.UNIDADE) e do nome da cor--(TB_COR.COR)

 SELECT ITEM.NUM_PEDIDO 
      , ITEM.NUM_ITEM
   , ITEM.COD_PRODUTO
   , ITEM.QUANTIDADE 
   , ITEM.PR_UNITARIO
   , PROD.ID_PRODUTO 
   , PROD.DESCRICAO  
   , TIPO.TIPO 
   , UNID.UNIDADE
   , COR.COR
 FROM TB_PRODUTO AS PROD 
INNER JOIN TB_TIPOPRODUTO AS TIPO
 ON TIPO.COD_TIPO = PROD.COD_TIPO
 INNER JOIN TB_UNIDADE AS UNID
 ON UNID.COD_UNIDADE = PROD.COD_UNIDADE
 INNER JOIN TB_ITENSPEDIDO AS ITEM
 ON ITEM.ID_PRODUTO = PROD.ID_PRODUTO
 INNER JOIN TB_COR AS COR
 ON ITEM.CODCOR=COR.CODCOR
 
 
 --11. Liste todos os pedidos (TB_PEDIDO) do vendedor MARCELO em Jan/2017;
 SELECT PED.DATA_EMISSAO 
      , PED.NUM_PEDIDO
   , VEND.NOME
 FROM TB_PEDIDO AS PED
 INNER JOIN TB_VENDEDOR AS VEND
 ON PED.CODVEN=VEND.CODVEN
 WHERE VEND.NOME ='MARCELO'
  AND YEAR(DATA_EMISSAO) = 2017
  AND MONTH(DATA_EMISSAO) = 1
  
  
 --Este exercício não especifica quais campos devem ser exibidos. Escolha você os campos que devem ser mostrados.
--12. Liste os nomes dos clientes (TB_CLIENTE.NOME) que efetuaram compras em janeiro de 2018;

 SELECT *
 FROM TB_PEDIDO AS PED
 INNER JOIN TB_CLIENTE AS CLI
 ON CLI.CODCLI = PED.CODCLI
 AND YEAR(DATA_EMISSAO) = 2018
 AND MONTH(DATA_EMISSAO) = 1
 
 --13. Liste os nomes de produtos (TB_PRODUTO.DESCRICAO) que foram vendidos em janeiro de 2019;
 
 SELECT  DISTINCT PROD.DESCRICAO
 FROM TB_PEDIDO AS PED
 INNER JOIN TB_ITENSPEDIDO AS ITEM
 ON ITEM.NUM_PEDIDO = PED.NUM_PEDIDO
 INNER JOIN TB_PRODUTO AS PROD
 ON ITEM.ID_PRODUTO = PROD.ID_PRODUTO
 AND YEAR(DATA_EMISSAO) = 2019
 AND MONTH(DATA_EMISSAO) = 1
 
 
 --14. Liste NUM_PEDIDO, VLR_TOTAL (PEDIDOS) e NOME (TB_CLIENTE). Mostre apenas pedidos de janeiro de 2017--do estado de SP.
 
 SELECT PED.NUM_PEDIDO 
     , PED.VLR_TOTAL
  , CLI.NOME 
FROM TB_PEDIDO AS PED
 INNER JOIN TB_CLIENTE AS CLI
 ON CLI.CODCLI = PED.CODCLI
 AND YEAR(PED.DATA_EMISSAO) = 2017
 AND MONTH(PED.DATA_EMISSAO) = 1
 AND CLI.ESTADO ='SP'
 
 
 --15. Liste o número do pedido e o valor dos pedidos de cor VERDE de 2012.
 
 SELECT ITEM.NUM_PEDIDO 
      , PED.VLR_TOTAL
   , YEAR(PED.DATA_EMISSAO) AS ANO
 FROM TB_ITENSPEDIDO AS ITEM
 INNER JOIN TB_PEDIDO AS PED
 ON PED.NUM_PEDIDO = ITEM.NUM_PEDIDO
 INNER JOIN TB_COR AS COR 
ON COR.CODCOR = ITEM.CODCOR
 WHERE COR.COR ='VERDE'
 AND YEAR(PED.DATA_EMISSAO) = 2012
 
 
 --16. Liste os produtos fornecidos pelos fornecedores que iniciam com a letra A;
 
 SELECT PROD.DESCRICAO
 FROM TB_FORNECEDOR FORNEC 
INNER JOIN TB_PROD_FORN PF 
ON FORNEC.COD_FORNECEDOR = PF.COD_FORNECEDOR
 INNER JOIN TB_PRODUTO PROD
 ON PF.ID_PRODUTO = PROD.ID_PRODUTO
 WHERE FORNEC.NOME LIKE ‘A%'
 
 
 --17. Liste os produtos que estão cadastrados na tabela TB_PRODUTO e que não estão em nenhum pedido--da tabela TB_ITENSPEDIDO e, também, retorne os produtos vendidos
 
 SELECT PROD.ID_PRODUTO
      ,PROD.DESCRICAO
      ,ITEM.NUM_PEDIDO
      ,ITEM.NUM_ITEM
      ,ITEM.ID_PRODUTO
 FROM TB_PRODUTO AS PROD
 LEFT JOIN TB_ITENSPEDIDO AS ITEM
 ON ITEM.ID_PRODUTO=PROD.ID_PRODUTO
 ORDER BY ITEM.ID_PRODUTO








